"""Writes the Emberlight Inn into src/main.tscn: its rooms, its cast and its doorways.

The scene text is generated rather than hand-edited because the inn is a table of positions --
four NPCs, seven examinable objects, four doorways -- and keeping it as a table means moving a
character is a one-line change here rather than hunting through a 5,000-line .tscn. Everything
between the two marker comments is owned by this script and rewritten whole, so it is safe to
re-run.

Each room is its own node, because Map draws one area at a time: all the game's maps share one
scene laid out side by side, so without that the player sees the kitchen and the hall at once.

The tile data itself is left empty here; apply_maps.py fills it, which is also what makes the
walkability check cover the inn.
"""
import os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_inn as bi
import oryx_atlas as oa

SCENE = os.path.join(oa.ROOT, "src", "main.tscn")
BEGIN = "; --- Emberlight Inn: generated by tools/apply_inn.py ---"
END = "; --- end Emberlight Inn ---"

# Resources already in the scene that the inn reuses.
TILESET = "7_po5fq"
GAMEBOARD_LAYER = "55_a8sfs"
GAMEPIECE = "11_yntrj"
INTERACTION = "19_sa6jd"
CONVERSATION = "14_b3y71"
POPUP = "34_qs25x"
AREA_TRANSITION = "37_6xxks"
GFX = {"smith": "18_2msel", "knight": "14_av6f5", "monk": "17_qgtho", "generic": "12_n5rm1"}

INN_DIR = "res://overworld/maps/inn"
HALL = "MainHall"

# Resources only the inn uses, as id -> (type, path).
RESOURCES = {
    "inn_quinn_script": ("Script", INN_DIR + "/quinn_conversation.gd"),
    "inn_patron_script": ("Script", INN_DIR + "/patron_conversation.gd"),
    "inn_quinn_intro": ("Resource", INN_DIR + "/quinn_intro.dtl"),
    "inn_quinn_waiting": ("Resource", INN_DIR + "/quinn_waiting.dtl"),
    "inn_quinn_end": ("Resource", INN_DIR + "/quinn_end.dtl"),
    "inn_captain": ("Resource", INN_DIR + "/patron_captain.dtl"),
    "inn_warrior": ("Resource", INN_DIR + "/patron_warrior.dtl"),
    "inn_medic": ("Resource", INN_DIR + "/patron_medic.dtl"),
}

# The design's three patrons. Quinn is handled separately: he has three timelines, not one.
PATRONS = [
    ("Captain", "captain", "knight", "inn_captain"),
    ("Warrior", "warrior", "generic", "inn_warrior"),
    ("Medic", "medic", "monk", "inn_medic"),
]

# "Two examinable story objects in Storage Attic, one in Kitchen, four in Main Hall." The cells are
# props drawn by build_inn.py, so the player examines the thing they can see.
EXAMINABLES = [
    ("StorageAttic", "AtticSacks", (63, 2), "attic_sacks"),
    ("StorageAttic", "AtticCasks", (67, 2), "attic_casks"),
    ("Kitchen", "KitchenPot", (38, 2), "kitchen_pot"),
    (HALL, "HallBoard", (45, 10), "hall_board"),
    (HALL, "HallHearth", (50, 10), "hall_hearth"),
    (HALL, "HallTap", (38, 10), "hall_tap"),
    (HALL, "HallWindow", (50, 15), "hall_window"),
]

# Doorway cell -> where the player lands, one cell short of the doorway back.
TRANSITIONS = [
    ("StorageAttic", "AtticToKitchen", (62, 6), (44, 4)),
    ("Kitchen", "KitchenToAttic", (45, 4), (62, 5)),
    ("Kitchen", "KitchenToHall", (38, 6), (38, 10)),
    (HALL, "HallToKitchen", (38, 9), (38, 5)),
]


def px(cell):
    x, y = bi.cell_to_pixel(cell)
    return "Vector2(%d, %d)" % (x, y)


def node(name, parent, body, node_type=None, instance=None):
    header = '[node name="%s"' % name
    if node_type:
        header += ' type="%s"' % node_type
    header += ' parent="%s"' % parent
    if instance:
        header += ' instance=ExtResource("%s")' % instance
    return header + "]\n" + body + "\n"


def layer(room, name):
    return node(name, "Field/Map/Inn/" + room,
                'tile_map_data = PackedByteArray("")\n'
                'tile_set = ExtResource("%s")\n'
                'script = ExtResource("%s")\n' % (TILESET, GAMEBOARD_LAYER),
                node_type="TileMapLayer")


def npc(room, name, gfx, position, script, properties):
    base = "Field/Map/Inn/%s/Gamepieces" % room
    out = node(name, base,
               'position = %s\nanimation_scene = ExtResource("%s")\n' % (position, GFX[gfx]),
               instance=GAMEPIECE)
    body = 'script = ExtResource("%s")\n' % script
    for key, value in properties:
        body += "%s = %s\n" % (key, value)
    out += node("Interaction", "%s/%s" % (base, name), body, instance=INTERACTION)
    out += node("InteractionPopup", "%s/%s/Interaction" % (base, name), "", instance=POPUP)
    return out


def block(resources):
    out = [BEGIN, ""]
    out.append(node("Inn", "Field/Map", "y_sort_enabled = true\n", node_type="Node2D"))

    for room in bi.ROOMS:
        out.append(node(room, "Field/Map/Inn", "y_sort_enabled = true\n", node_type="Node2D"))
        for name in ("Ground", "Walls", "Decoration"):
            out.append(layer(room, name))
        out.append(node("Gamepieces", "Field/Map/Inn/" + room, "y_sort_enabled = true\n",
                        node_type="Node2D"))

    out.append(npc(
        HALL, "Quinn", "smith", px(bi.SPAWNS["quinn"]), "inn_quinn_script",
        [("intro_timeline", 'ExtResource("inn_quinn_intro")'),
         ("waiting_timeline", 'ExtResource("inn_quinn_waiting")'),
         ("end_timeline", 'ExtResource("inn_quinn_end")')]))

    for name, spawn, gfx, timeline in PATRONS:
        out.append(npc(HALL, name, gfx, px(bi.SPAWNS[spawn]), "inn_patron_script",
                       [("timeline", 'ExtResource("%s")' % timeline)]))

    for room, name, cell, slug in EXAMINABLES:
        res_id = "inn_ex_" + slug
        resources[res_id] = ("Resource", "%s/examine_%s.dtl" % (INN_DIR, slug))
        base = "Field/Map/Inn/%s/Gamepieces" % room
        out.append(node(name, base,
                        'position = %s\nscript = ExtResource("%s")\n'
                        'timeline = ExtResource("%s")\n' % (px(cell), CONVERSATION, res_id),
                        instance=INTERACTION))
        out.append(node("InteractionPopup", "%s/%s" % (base, name), "emote = 2\n", instance=POPUP))

    for room, name, cell, arrival in TRANSITIONS:
        out.append(node(name, "Field/Map/Inn/%s/Gamepieces" % room,
                        "position = %s\narrival_coordinates = %s\n" % (px(cell), px(arrival)),
                        instance=AREA_TRANSITION))

    out.append(END)
    return "\n".join(out) + "\n"


def main():
    text = open(SCENE, encoding="utf-8").read()

    resources = dict(RESOURCES)
    body = block(resources)

    lines = []
    for res_id, (res_type, path) in sorted(resources.items()):
        line = '[ext_resource type="%s" path="%s" id="%s"]' % (res_type, path, res_id)
        if line not in text:
            lines.append(line)
    if lines:
        last = text.rindex("[ext_resource ")
        end = text.index("\n", last) + 1
        text = text[:end] + "\n".join(lines) + "\n" + text[end:]
        print("  added %d ext_resources" % len(lines))

    if BEGIN in text:
        start = text.index(BEGIN)
        finish = text.index(END, start) + len(END) + 1
        text = text[:start] + body + text[finish:]
        print("  replaced the inn block")
    else:
        anchor = text.index('[node name="Overlay" type="Node2D" parent="Field/Map"')
        text = text[:anchor] + body + "\n" + text[anchor:]
        print("  inserted the inn block")

    open(SCENE, "w", encoding="utf-8", newline="\n").write(text)
    print("  wrote", SCENE)


if __name__ == "__main__":
    main()
